[package]
name = "core"
version = "0.1.0"
edition = "2021"


[dependencies]
common = { path = "../common" }
plugin_api = { path = "../plugin_api" }
async-trait = "0.1.53"
stretto = { version = "0.4.5", features = ["async"] }
tokio = { version = "1.18.2", features = ["full"] }