name: Build

on:
  push:
    branches-ignore:
      - renovate/*
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true


env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Rust Setup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1
      - name: Build
        run: cargo build -r
      - name: Run tests
        run: cargo test -r
      - name: Run benchmarks
        run: cargo bench
  docs:
    name: Docs
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Rust Setup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1
      - name: Generate Docs
        run: cargo doc
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: target/doc/ # The folder containing the documentation.