name: Build,Test,Docs

on:
  push:
    branches-ignore:
      - renovate/*
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true


env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
        with:
          cache-key: ${{ runner.os }}/${{ github.ref }}

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            **/target/
            **/Cargo.lock
          key: ${{ runner.os }}/${{ github.ref }}
      - name: Build
        run: cargo build -r
      - name: Run tests
        run: cargo test -r
      - name: Run benchmarks
        run: cargo bench
  docs:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            **/target/
            **/Cargo.lock
          key: ${{ runner.os }}/${{ github.ref }}
      - name: Generate Docs
        run: cargo doc
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: target/doc/ # The folder containing the documentation.