name: Generate Docs

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: branch_name
    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ./target/
          Cargo.lock
        key: docs>${{ runner.os }}-${{ steps.branch_name.outputs.branch }}
    - name: Generate Docs
      run: cargo doc
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: target/doc/ # The folder containing the documentation.
