name: Build and Release

on:
  release:
    types:
      - released
      - prereleased
  workflow_dispatch:

#on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_publish:
    strategy:
      matrix:
        include:

          # Linux
          - target: "x86_64-unknown-linux-gnu"
            platform: "ubuntu-latest"
            export: "x86_64-linux"

            # Windows
          - target: "x86_64-pc-windows-msvc"
            platform: "windows-latest"
            export: "x86_64-windows"
            file_extension: ".exe"

            # MacOS
          - target: "x86_64-apple-darwin"
            platform: "macos-latest"
            export: "x86_64-macos"

    name: Build Binary for ${{ matrix.export }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Rust Setup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1
      - name: Build
        run: cargo build --target ${{ matrix.target }} --release
      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          release_id: ${{ steps.create_release.outputs.id }}
          file: target/${{ matrix.target }}/release/object_database${{ matrix.file_extension }}
          asset_name: object_database-${{ matrix.export }}${{ matrix.file_extension }}
          release_name: generated ${{ github.sha }}
          prerelease: true
          body: | 
            Autogenerated release for branch/tag ${{ github.ref_name }}

